biblio/urls.py
from django.contrib import admin
from django.urls import path, include
from contact.views import MessageAddView
from shelf.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shelf/', include('shelf.urls')),
    path('contact/', MessageAddView.as_view()),
    path('', MainPageView.as_view(), name = "home")
]

shelf/urls.py
from . import views
from django.urls import path
app_name = 'shelf'
urlpatterns = [
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

contact/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f'message from {self.name}'

rental/models.py
from django.db import models
from django.contrib.auth.models import  User
from shelf.models import BookItem
from django.utils.timezone import now

class Rental(models.Model):
    who = models.ForeignKey(User, on_delete=models.CASCADE)
    what = models.ForeignKey(BookItem, on_delete=models.CASCADE)
    when = models.DateTimeField(default=now)
    returned = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.who.username} - {self.what.book.title} - {self.what.cat_number}'

shelf/models.py
# do zgodności z Python 2
# from __future__ import unicode_literals, absolute_import, print_function
# from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.urls import reverse
# from raport.models import raport  ( z innej aplikacji)
from django.utils.translation import ugettext_lazy as _

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('shelf:author-detail', args=[str(self.id)])

class Publisher(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    # author = models.ForeignKey(Author, on_delete=models.CASCADE)   #przy zmianie typu pola
    # lepiej utworzyć nowe, niz zmieniać stare
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)

    # raport = models.ForeignKey("raports.Raport") jeśli FK z innej aplikacji
    # którą wcześniej trzeba zaimportować

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shelf:book-detail', args=[str(self.id)])

class BookEdition(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="editions")
    isbn = models.CharField(max_length=17)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f'{self.book.title} {self.publisher.name}'


COVER_TYPES = (
    ('soft', 'Soft'),  #  (wartość w bazie, wartość wyświetlana)
    ('hard', 'Hard')
)
class BookItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    edition = models.ForeignKey(BookEdition, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True)
    cat_number = models.CharField(max_length=30)
    cover_type = models.CharField(max_length=4, choices=COVER_TYPES)
    def __str__(self):
        return f'{self.edition} {self.get_cover_type_display()}'

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

    # def clean_name(self):
    #     data = self.cleaned_data.get('title')
    #     if "D" in data:
    #         return data
    #     else:
    #         raise forms.ValidationError('imię musi zawierać D')

contact/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, FormView, CreateView
from  .models import Message
from .forms import MessageForm, ContactForm
from django.urls import reverse_lazy


# class MessageDetailView(DetailView):
#     model = Message

######################################################################
# class MessageAddView(FormView):
#     form_class = MessageForm
#     template_name = 'contact/message_form.html'
#     success_url = reverse_lazy('shelf:books')
#
#     def form_valid(self, form):
#         form.save()
#         return super(MessageAddView, self). form_valid(form)

##############################################################################

# class MessageCreateView(CreateView):
#     model = Message
#     fields = '__all__'
#     def get_success_url(self):
#         return reverse_lazy('shelf:books')

###########################################################

class MessageAddView(FormView):
    form_class = ContactForm
    template_name = 'contact/message_form.html'
    success_url = reverse_lazy('shelf:books')

    def form_valid(self, form):
       # print(form.cleaned_data)
        Message.objects.create(**form.cleaned_data)
        return super(MessageAddView, self).form_valid(form)

#####################################################################

rental/views.py
from django.shortcuts import render

# Create your views here.

shelf/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import DetailView, ListView, TemplateView
from  .models import Author, Book
# from django.views import View

# class MainPageView(TemplateView):
#     def get(self, request, *args, **kwargs):
#         return render(HttpResponse('OK'))

# index_view = MainPageView.as_view()

class MainPageView(TemplateView):
    template_name = 'index.html'

class AuthorListView(ListView):
    model = Author

class AuthorDetailView(DetailView):
    model = Author

class BookListView(ListView):
    model = Book

class BookDetailView(DetailView):
    model = Book

contact/templates/contact/message_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

contact/templates/contact/message_form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <button type="submit">send</button>
</form>
{% endblock %}

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'shelf:authors' %}">Powrót do listy autorów</a>
  <h1>{{ author }}</h1>

        {% if author.book_set.all %}
              <h2> Książki tegoż autora:</h2>
        {% endif %}

    <ul>
      {% for book in author.book_set.all %}
          <li>
              <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>,
                {% for cat in book.categories.all %}
                   {{ cat }}{% if not forloop.last %}, {% endif %}
                {% endfor %} </li>
        {% empty %}
             <p>There are no books of this author in the library.</p>
        {% endfor %}
    </ul>




{% endblock %}

shelf/templates/shelf/author_list.html
{% extends 'base.html' %}

{% block content %}
    {% if author_list %}
    <ul>
        {% for author in object_list %}
          <li><a href="{{ author.get_absolute_url }}">{{ author }}, </a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}

{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %} {% load shelf_tags %}

{% block content %}
<ul>

    <a href="{% url 'shelf:books' %}">Powrót do listy książek</a>

    <h2>Tytuł: {{ book }}</h2>

    <h3>Autorzy:</h3>
        {% for author in book.authors.all %}
            <a href="{{ author.get_absolute_url }}">{{ author }}</a>
                {% if not forloop.last %} , {% endif %}
        {% empty %}
            <p>Nie ma autorów?</p>
        {% endfor %}

    <h3>Kategorie:</h3>
        {% for cat in book.categories.all %}
           <p>{{ cat }}</p>
        {% empty %}
            <p>Nie ma kategorii</p>
        {% endfor %}


    <h3>Wydania:</h3>

        {% show_editions book %}


<!--        {% for ed in book.editions.all %}-->
<!--                <p>{{ ed.publisher }} ({{ ed.date|pub_date }})</p>-->
<!--        {% empty %}-->
<!--                 <p>There are no editions of this book in the library.</p>-->
<!--        {% endfor %}-->

</ul>

{% endblock %}

shelf/templates/shelf/book_list.html
{% extends 'base.html' %}

{% block content %}
    {% if book_list %}
    <ul>
        {% for book in book_list %}
          <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>

            <p> {% for author in book.authors.all %}
                    <a href="{{ author.get_absolute_url }}">{{ author }}</a>
                        {% if not forloop.last %} , {% endif %}

                {% empty %}
                   Nie ma autorów?>
                {% endfor %}</p>

            <p> {% for cat in book.categories.all %}
                   {{ cat }}{% if not forloop.last %}, {% endif %}
                {% endfor %}</p>

        {% endfor %}
    </ul>

    {% else %}
        <p>There are no books in the whole library.</p>
    {% endif %}

{% endblock %}

shelf/templates/tags/show_editions.html
{% load shelf_tags %}

{% for edition in editions %}
        <p>{{ edition.publisher }} ({{ edition.date|pub_date }})</p>
{% empty %}
         <p>There are no editions of this book in the library.</p>
{% endfor %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Main {% endblock %}</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body style="margin-top: 2px; padding: 0">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

	{% include 'navbar.html' %}

      </div>

         <div class="col-sm-10 ">{% block content %}{% endblock %}</div>

    </div>
  </div>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
Hello
{% endblock %}

templates/navbar.html
<div style="margin-top: 2px; padding: 0">
	<ul>
		<li><a href="{% url 'home' %}">Home</a></li>
		<li><a href="{% url 'shelf:books' %}">Książki</a></li>
		<li><a href="{% url 'shelf:authors' %}">Autorzy</a></li>
	</ul>
</div>